### ISSUE TITLE
examples\graph\src\nodes.rs fails to build

### ISSUE THREAD

**Issue by kev009** [woboq/qmetaobject-rs#108]
On windows with recent rust(1.46) it fails to build

**Comment by ratijas** [comment]
Hi, @kev009. Thanks for the report. Unfortunately, I can not test it on windows right now. Could you, please, provide build log and more details?

**Comment by kev009** [comment]
```
PS C:\Users\kev009\Documents\rust\qmetaobject-rs> cargo build
warning: `extern` fn uses type `std::cell::RefCell<dyn QObject>`, which is not FFI-safe
   --> qmetaobject\src\lib.rs:569:51
    |
569 | pub unsafe extern "C" fn RustObject_metaObject(p: *mut RefCell<dyn QObject>) -> *const QMetaObject {
    |                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^ not FFI-safe
    |
    = note: `#[warn(improper_ctypes_definitions)]` on by default
    = help: consider adding a `#[repr(C)]` or `#[repr(transparent)]` attribute to this struct
    = note: this struct has unspecified layout

warning: `extern` fn uses type `std::cell::RefCell<dyn QObject>`, which is not FFI-safe
   --> qmetaobject\src\lib.rs:575:49
    |
575 | pub unsafe extern "C" fn RustObject_destruct(p: *mut RefCell<dyn QObject>) {
    |                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^ not FFI-safe
    |
    = help: consider adding a `#[repr(C)]` or `#[repr(transparent)]` attribute to this struct
    = note: this struct has unspecified layout

warning: 2 warnings emitted

   Compiling graph v0.1.0 (C:\Users\kev009\Documents\rust\qmetaobject-rs\examples\graph)
error[E0433]: failed to resolve: unresolved import
  --> examples\graph\src\nodes.rs:30:18
   |
30 |     cpp!(unsafe [s as "NoisyNode**", item_ptr as "QQuickItem*"] {
   |                  ^
   |                  |
   |                  unresolved import
   |                  help: a similar path exists: `lazy::core`
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: unresolved import
  --> examples\graph\src\nodes.rs:30:38
   |
30 |     cpp!(unsafe [s as "NoisyNode**", item_ptr as "QQuickItem*"] {
   |                                      ^^^^^^^^
   |                                      |
   |                                      unresolved import
   |                                      help: a similar path exists: `lazy::core`
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: unresolved import
  --> examples\graph\src\nodes.rs:30:5
   |
30 | /     cpp!(unsafe [s as "NoisyNode**", item_ptr as "QQuickItem*"] {
31 | |         if (!*s && item_ptr) {
32 | |             *s = new NoisyNode(item_ptr->window());
33 | |         }
34 | |     });
   | |       ^
   | |       |
   | |_______unresolved import
   |         help: a similar path exists: `lazy::core`
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: unresolved import
  --> examples\graph\src\nodes.rs:38:18
   |
38 |     cpp!(unsafe [s as "NoisyNode**", rect as "QRectF"] {
   |                  ^
   |                  |
   |                  unresolved import
   |                  help: a similar path exists: `lazy::core`
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: unresolved import
  --> examples\graph\src\nodes.rs:38:38
   |
38 |     cpp!(unsafe [s as "NoisyNode**", rect as "QRectF"] {
   |                                      ^^^^
   |                                      |
   |                                      unresolved import
   |                                      help: a similar path exists: `lazy::core`
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: unresolved import
  --> examples\graph\src\nodes.rs:38:5
   |
38 | /     cpp!(unsafe [s as "NoisyNode**", rect as "QRectF"] {
39 | |         if (*s) {
40 | |             (*s)->setRect(rect);
41 | |         }
42 | |     });
   | |       ^
   | |       |
   | |_______unresolved import
   |         help: a similar path exists: `lazy::core`
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: unresolved import
  --> examples\graph\src\nodes.rs:47:18
   |
47 |     cpp!(unsafe [s as "GridNode**", rect as "QRectF"] {
   |                  ^
   |                  |
   |                  unresolved import
   |                  help: a similar path exists: `lazy::core`
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: unresolved import
  --> examples\graph\src\nodes.rs:47:37
   |
47 |     cpp!(unsafe [s as "GridNode**", rect as "QRectF"] {
   |                                     ^^^^
   |                                     |
   |                                     unresolved import
   |                                     help: a similar path exists: `lazy::core`
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: unresolved import
  --> examples\graph\src\nodes.rs:47:5
   |
47 | /     cpp!(unsafe [s as "GridNode**", rect as "QRectF"] {
48 | |         if (!*s) *s = new GridNode;
49 | |         (*s)->setRect(rect);
50 | |     });
   | |       ^
   | |       |
   | |_______unresolved import
   |         help: a similar path exists: `lazy::core`
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: unresolved import
  --> examples\graph\src\nodes.rs:56:18
   |
56 |     cpp!(unsafe [s as "LineNode**", size as "float", spread as "float", color as "QColor"] {
   |                  ^
   |                  |
   |                  unresolved import
   |                  help: a similar path exists: `lazy::core`
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: unresolved import
  --> examples\graph\src\nodes.rs:56:37
   |
56 |     cpp!(unsafe [s as "LineNode**", size as "float", spread as "float", color as "QColor"] {
   |                                     ^^^^
   |                                     |
   |                                     unresolved import
   |                                     help: a similar path exists: `lazy::core`
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: unresolved import
  --> examples\graph\src\nodes.rs:56:54
   |
56 |     cpp!(unsafe [s as "LineNode**", size as "float", spread as "float", color as "QColor"] {
   |                                                      ^^^^^^
   |                                                      |
   |                                                      unresolved import
   |                                                      help: a similar path exists: `lazy::core`
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: unresolved import
  --> examples\graph\src\nodes.rs:56:73
   |
56 |     cpp!(unsafe [s as "LineNode**", size as "float", spread as "float", color as "QColor"] {
   |                                                                         ^^^^^
   |                                                                         |
   |                                                                         unresolved import
   |                                                                         help: a similar path exists: `lazy::core`
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: unresolved import
  --> examples\graph\src\nodes.rs:56:5
   |
56 | /     cpp!(unsafe [s as "LineNode**", size as "float", spread as "float", color as "QColor"] {
57 | |         if (!*s) *s = new LineNode(size, spread, color);
58 | |     });
   | |       ^
   | |       |
   | |_______unresolved import
   |         help: a similar path exists: `lazy::core`
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: unresolved import
  --> examples\graph\src\nodes.rs:64:18
   |
64 |     cpp!(unsafe [s as "LineNode**", rect as "QRectF", samples_ptr as "double*",
   |                  ^
   |                  |
   |                  unresolved import
   |                  help: a similar path exists: `lazy::core`
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: unresolved import
  --> examples\graph\src\nodes.rs:64:37
   |
64 |     cpp!(unsafe [s as "LineNode**", rect as "QRectF", samples_ptr as "double*",
   |                                     ^^^^
   |                                     |
   |                                     unresolved import
   |                                     help: a similar path exists: `lazy::core`
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: unresolved import
  --> examples\graph\src\nodes.rs:64:55
   |
64 |     cpp!(unsafe [s as "LineNode**", rect as "QRectF", samples_ptr as "double*",
   |                                                       ^^^^^^^^^^^
   |                                                       |
   |                                                       unresolved import
   |                                                       help: a similar path exists: `lazy::core`
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: unresolved import
  --> examples\graph\src\nodes.rs:65:18
   |
65 |                  samples_len as "std::size_t"] {
   |                  ^^^^^^^^^^^
   |                  |
   |                  unresolved import
   |                  help: a similar path exists: `lazy::core`
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: unresolved import
  --> examples\graph\src\nodes.rs:64:5
   |
64 | /     cpp!(unsafe [s as "LineNode**", rect as "QRectF", samples_ptr as "double*",
65 | |                  samples_len as "std::size_t"] {
66 | |         if (!*s) return;
67 | |         QList<qreal> samples;
...  |
70 | |         (*s)->updateGeometry(rect, samples);
71 | |     });
   | |       ^
   | |       |
   | |_______unresolved import
   |         help: a similar path exists: `lazy::core`
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: unresolved import
  --> examples\graph\src\main.rs:37:22
   |
37 |         cpp!(unsafe [obj as "QQuickItem *"] { obj->setFlag(QQuickItem::ItemHasContents); });
   |                      ^^^
   |                      |
   |                      unresolved import
   |                      help: a similar path exists: `lazy::core`
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: unresolved import
  --> examples\graph\src\main.rs:37:9
   |
37 |         cpp!(unsafe [obj as "QQuickItem *"] { obj->setFlag(QQuickItem::ItemHasContents); });
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |         |
   |         unresolved import
   |         help: a similar path exists: `lazy::core`
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to 21 previous errors

For more information about this error, try `rustc --explain E0433`.
error: could not compile `graph`.
```

**Comment by ogoffart** [comment]
Could be caused by https://github.com/mystor/rust-cpp/pull/78  but i don't understand why that wouldn't work
Maybe because that example is still using the edition 2015.

**Comment by ogoffart** [comment]
I can reproduce on linux with rust 1.46

**Comment by ogoffart** [comment]
Yes, that's it: the problem is that `::core`  does not work with edition 2015 without `extern crate core;`

**Comment by ratijas** [comment]
I you don't feel like committing it by yourself, then I'll fix &  push it later overnight.

**Comment by ratijas** [comment]
Interestingly enough, I haven't found any source stating that default edition was changed to 2018. So, it should be still 2015. But new code generated by 3rd-party crates won't work in 2015, which actually causes the issue.

I haven't been able to reproduce until I run `cargo update`. So yeah, it must be something introduced by 3rd-parties. Kinda shame on them for breaking consumers' code on patch version change.

<details>
    <summary>Update log</summary>
    I suppose, the interesting part here is <code>cpp v0.5.4 -> v0.5.5</code>. Recompiled with old one — and it worked again!
    <pre><code>Updating crates.io index
Updating aho-corasick v0.7.10 -> v0.7.13
Updating autocfg v1.0.0 -> v1.0.1
Updating cc v1.0.52 -> v1.0.59
Updating chrono v0.4.11 -> v0.4.15
Updating cpp v0.5.4 -> v0.5.5
Updating cpp_build v0.5.4 -> v0.5.5
Updating cpp_common v0.5.4 -> v0.5.5
Updating cpp_macros v0.5.4 -> v0.5.5
Updating libc v0.2.69 -> v0.2.76
Updating log v0.4.8 -> v0.4.11
Updating num-integer v0.1.42 -> v0.1.43
Updating num-traits v0.2.11 -> v0.2.12
Updating ppv-lite86 v0.2.6 -> v0.2.9
Updating proc-macro2 v1.0.10 -> v1.0.20
Updating procedural-masquerade v0.1.6 -> v0.1.7
Updating quote v1.0.3 -> v1.0.7
Updating redox_syscall v0.1.56 -> v0.1.57
Updating regex v1.3.7 -> v1.3.9
Updating regex-syntax v0.6.17 -> v0.6.18
Updating remove_dir_all v0.5.2 -> v0.5.3
Updating syn v1.0.18 -> v1.0.40
Updating time v0.1.43 -> v0.1.44
Updating unicode-xid v0.2.0 -> v0.2.1
  Adding wasi v0.10.0+wasi-snapshot-preview1
Updating winapi v0.3.8 -> v0.3.9</code></pre>
</details>

**Comment by ratijas** [comment]
Aaaaand the reason why only `graph` example was failing is... because it was one of the two packages left out on Rust 2015 — other one would be `qmlextensionplugins`, but only `graph` uses the `cpp!` macro.

Case solved & closed. Patch #109 is on its way.
